name: docker-stable
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      version:
        description: "TruffleRuby Version"
        required: true

jobs:
  stable:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: truffleruby
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        file: tool/dockerfiles/stable.dockerfile
        build-args: |
          TRUFFLERUBY_VERSION=${{ github.event.inputs.version }}
        tags: |
          ghcr.io/truffleruby/truffleruby:stable
          ghcr.io/truffleruby/truffleruby:latest
          ghcr.io/truffleruby/truffleruby:${{ github.event.inputs.version }}
        push: true

  stable-slim:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: truffleruby
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        file: tool/dockerfiles/stable-slim.dockerfile
        build-args: |
          TRUFFLERUBY_VERSION=${{ github.event.inputs.version }}
        tags: |
          ghcr.io/truffleruby/truffleruby:stable-slim
          ghcr.io/truffleruby/truffleruby:latest-slim
          ghcr.io/truffleruby/truffleruby:${{ github.event.inputs.version }}-slim
        push: true
