name: docker-nightly
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # At 05:00. # https://crontab.guru/#0_5_*_*_*

jobs:
  nightly:
    if: github.repository == 'truffleruby/truffleruby'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: truffleruby
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        file: tool/dockerfiles/nightly.dockerfile
        tags: ghcr.io/truffleruby/truffleruby:nightly
        push: true

  nightly-slim:
    if: github.repository == 'truffleruby/truffleruby'
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: truffleruby
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        file: tool/dockerfiles/nightly-slim.dockerfile
        tags: ghcr.io/truffleruby/truffleruby:nightly-slim
        push: true
